directory = "_maps/map_files/biodome/modules/"

[rooms.cage_1]
modules = ["cage_1_axolotl.dmm"]

[rooms.cage_2]
modules = ["cage_2_amoung.dmm"]

[rooms.cage_3]
modules = ["cage_3_rabbit.dmm"]

[rooms.cage_4]
modules = ["cage_4_cockroach.dmm"]
